name: Запуск на сервере

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Тест SSH подключения
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_IP }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: echo "Успешное подключение!"

      - name: Настройка SSH
        run: |
          mkdir -p ~/.ssh

      - name: Проверка .prod.env
        run: |
          if [ ! -f .prod.env ]; then
            echo "::error::.prod.env not found!"
            exit 1
          fi

      - name: отправка .prod.env
        uses: appleboy/scp-action@v1
        with:
          host: ${{ secrets.SERVER_IP }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          source: ".prod.env"
          target: "/tmp/${GITHUB_RUN_ID}.env"

      - name: Деполой
        uses: appleboy/ssh-action@v1
        with:
          host: ${{ secrets.SERVER_IP }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            chmod +x ~/deploy.sh
            ~/deploy.sh "/tmp/${GITHUB_RUN_ID}.env"